app:
  name: CurrencyExchangeApp
  port: :3000

database:
  # host: localhost
  # port: :3306
  # user: root
  # password: 533934
  # name: currency_exchange
  dsn: "root:533934@tcp(127.0.0.1:3306)/exchangeapp?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenConns: 100